### ISSUE TITLE
add git to bionic stack build image

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpack/stacks#2]

**Comment by ameyer-pivotal** [comment]
@mgibson1121 This change should be present on `0.0.1-rc.2`. For acceptance:

```bash
docker run -it --rm cnbs/build:0.0.1-rc.2 bash
git version
```

You should see a version number if git is present.

**Comment by mgibson1121** [comment]
This story passes acceptance

**Comment by ekcasey** [comment]
will ship in `v0.0.1`
