### ISSUE TITLE
setup pipeline for bionic stack

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpack/stacks#8]
trigger on `ubuntu:bionic updates`

**Comment by ameyer-pivotal** [comment]
@sclevine pipeline URL: https://ci.buildpacks.io/teams/main/pipelines/stacks

**Comment by mgibson1121** [comment]
Moving to done because this seems like a chore.

**Comment by ameyer-pivotal** [comment]
@mgibson1121 I'd argue it's not a chore because it has user-facing value/impact. To verify, just note that we retrigger builds based on updates to the `ubuntu:bionic` image (the resource called `ubuntu-bionic-image` in the pipeline https://ci.buildpacks.io/teams/main/pipelines/stacks).

The value that it adds is that users of our bionic stack will inherit updates to the root bionic image.
